export const companies = [
  { name: "BAE SYSTEMS PLC", domain: "baesystems.com" },
  { name: "Bank of America", domain: "bankofamerica.com" },
  { name: "Velocity Academy", domain: "" },
  { name: "RUSKIN MILL TRUST LIMITED", domain: "ruskinmilltrust.org" },
  { name: "ACCENTURE (UK) LIMITED", domain: "accenture.com" },
  { name: "DHL Supply Chain limited", domain: "dhl.com" },
  { name: "Veolia UK", domain: "veolia.co.uk" },
  { name: "MORGAN STANLEY UK LIMITED", domain: "morganstanley.com" },
  { name: "VODAFONE LIMITED", domain: "vodafone.com" },
  { name: "TRIMMING SHOP 007 LTD", domain: "" },
  { name: "SHARPNESS DOCK LIMITED", domain: "victoriagroup.co.uk" },
  { name: "VOLKERSERVICES LIMITED", domain: "volkerwessels.co.uk" },
  { name: "SURESERVE GROUP PLC", domain: "sureserve.co.uk" },
  { name: "Hart District Council", domain: "hart.gov.uk" },
  { name: "BDR Group", domain: "bdrgroup.co.uk" },
  { name: "TATA CONSULTANCY SERVICES LIMITED", domain: "tcs.com" },
  { name: "Royal Navy", domain: "royalnavy.mod.uk" },
  { name: "JUST I.T. TRAINING LIMITED", domain: "justit.co.uk" },
  { name: "PLASTIC OMNIUM AUTOMOTIVE LIMITED", domain: "plasticomnium.com" },
  { name: "Science and Technology Facilities Council", domain: "ukri.org" },
  { name: "CAPULA LIMITED", domain: "capula.co.uk" },
  { name: "ZURICH EMPLOYMENT SERVICES LIMITED", domain: "zurich.co.uk" },
  { name: "MULTIDATA (EUROPE) LTD", domain: "multidata.co.uk" },
  { name: "GLOBAL BANKING SCHOOL LTD", domain: "globalbankingschool.com" },
  { name: "THALES UK LIMITED", domain: "thalesgroup.com" },
  { name: "MIGRANT HELPLINE", domain: "migranthelpuk.org" },
  { name: "BT GROUP PLC", domain: "bt.com" },
  { name: "THE PENINSULAR AND ORIENTAL STEAM NAVIGATION COMPANY", domain: "dpworld.com" },
  { name: "TPT Retirement Solutions", domain: "tpt.org.uk" },
  { name: "JUNGLE IT LTD", domain: "jungleit.co.uk" },
  { name: "APOLLO TECHNOLOGY SOLUTIONS LTD", domain: "apollotechnologysolutions.com" },
  { name: "Deta Electrical Limited", domain: "deta.co.uk" },
  { name: "ROLLS-ROYCE PLC", domain: "rolls-royce.com" },
  { name: "CAPGEMINI UK PLC", domain: "capgemini.com" },
  { name: "Sweethaven - Cambrian Trust", domain: "sweethaven.com" },
  { name: "ACCRUETEK CONSULTING LIMITED", domain: "accruetek.com" },
  { name: "H20 IT LTD", domain: "h20-it.co.uk" },
  { name: "Lloyds Banking Group", domain: "lloydsbankinggroup.com" },
  { name: "HYBRIT SERVICES LTD", domain: "hybrit.co.uk" },
  { name: "SCHNEIDER ELECTRIC LIMITED", domain: "se.com" },
  { name: "Allianz Commercial", domain: "allianz.com" },
  { name: "REMIT GROUP LIMITED", domain: "remit.co.uk" },
  { name: "E.ON UK PLC", domain: "eonenergy.com" },
  { name: "South Hunsley School and Sixth Form College", domain: "southhunsley.org.uk" },
  { name: "KEIBRA LTD", domain: "keibra.com" },
  { name: "DATASYSTEMS (MIDLANDS) LIMITED", domain: "datasystems.co.uk" },
  { name: "VELOCITY IT ACADEMY LIMITED", domain: "" },
  { name: "Reconfort Ltd", domain: "reconfortrisk.com" },
  { name: "ISON HARRISON LIMITED", domain: "isonharrison.co.uk" },
  { name: "CORE DIAGNOSTICS LIMITED", domain: "corediagnostics.co.uk" },
  { name: "AtkinsRéalis", domain: "atkinsrealis.com" },
];